version: '3'

services:
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    env_file: ./.env
    image: eyupersoy/backend:v1.0.0
    ports:
      - 5000:5000
    depends_on:
      - mysql_db
      - redis
    environment:
      - MASTER_DB=mysql_db
      - REDIS_HOST=redis
    networks:
      - bizleal_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis-data:/redis-data
    ports:
      - 6379
    networks:
      - bizleal_network

  mysql_db:
    image: mysql
    container_name: 'mysql_db'
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Mhp.1923
      - MYSQL_DATABASE=bizleal
      - BACKUP_DIR=/backups
    networks:
      - bizleal_network
    volumes:
      - shared-data:/backups
      - db-data:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/

  backup:
    image: databack/mysql-backup
    user: "0"
    container_name: 'backup'
    depends_on:
      - mysql_db
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - shared-data:/backups
    environment:
      - DB_DUMP_TARGET=/backups
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_USER=${USER}
      - DB_DUMP_FREQ=60
      - DB_DUMP_BEGIN=+5
      #  - DB_DUMP_CRON=*/5 * * * *
      - DB_SERVER=mysqldb
      - DB_NAMES=bizleal
      - DB_DUMP_SAFECHARS="no-colons
    networks:
      - bizleal_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyadmin
    depends_on:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: unless-stopped
    networks:
      - bizleal_network
    ports:
      - 8081:80

volumes:
  shared-data:
    driver: local
  db-data:
    driver: local
  mysql_config:

    null
networks:
  bizleal_network:
    driver: bridge
