apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bizleal-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bizleal-api-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60