apiVersion: v1
kind: ConfigMap
metadata:
  name: bizleal-api-config
  namespace: bizleal
data:
  PORT: "5000"
  MYSQL_DATABASE: "bizleal"
  USER: "root"
  REDIS_PORT: "6379"
  MASTER_DB: mysql-primary #service name for mysql master database
  READ_ONLY_DB:  mysql-secondary-headless #service name for mysql replica databases
  REDIS_HOST: redis-service
