apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizleal-api-deployment
  namespace: bizleal
  labels:
    app: bizleal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bizleal-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bizleal-api
    spec:
      imagePullSecrets:
        - name: bizleal-api-sercret
      containers:
        - name: bizlea-api
          image: eyupersoy/bizleal-api
          imagePullPolicy: Always
          command: ["yarn", "start"]
          ports:
            - containerPort: 5000
          envFrom:
          - configMapRef:
              name: bizleal-api-config
          - secretRef:
              name: mysqldb-secret

---

apiVersion: v1
kind: Service
metadata:
  name: bizleal-api-service
  namespace: bizleal
spec:
  selector:
    app: bizleal-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
