apiVersion: v1
kind: ConfigMap
metadata:
  name: bizleal-api-config
  namespace: bizleal
data:
  PORT: "5000"
  MYSQL_DATABASE: "bizleal"
  USER: "root"
  REDIS_PORT: "6379"
  MYSQL_HOST: mysqldb-service
  REDIS_HOST: redis-service
