apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: bizleal
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.global-static-ip-name: bizleal-api-static-ip
spec:
  tls:
    - hosts:
      - api.bizleal.net
      secretName: ssl-cert-production
  rules:
  - host: api.bizleal.net
    http:
      paths:
        - path: '/'
          pathType: Prefix
          backend:
            service:
              name: bizleal-api-service
              port:
                number: 5000
        - path: '/phpmyadmin'
          pathType: Exact
          backend:
            service:
              name: phpmyadmin-service
              port:
                number: 8082