architecture: replication
primary: 
  resources: 
    requests:
      cpu: 100m
      memory: 256Mi
secondary: 
  replicaCount: 1
  resources:
    requests:
       cpu: 100m
       memory: 256Mi
auth:
  rootPassword: Mhp.1923
  database: "bizleal"
persistence: 
  storageClass: "standard"


# helm install mysql --namespace=bizleal --values kubernetes/mysql-bitnami-k8/mysql-values.yaml bitnami/mysql
