name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build NODE JS bizleal-api
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build node js bizleal-api
      run: |
        docker build -t eyupersoy/bizleal-api:1.0.2 .
    - name: docker push to repository
      run: |
        docker push eyupersoy/bizleal-api:1.0.0

